import type {ImportPreview,ImportDashboard,ImportPreviewRecord,ParsedImportFile} from "../domain/imports.js";
import {validImportId,safeImportedTransactionLink,validateSourceFile,validateParsedImport,previewAudit,secureRecordUpdate,sourceFileLabel} from "./signal-import-model.js";
const ok=(condition:unknown,label:string)=>{if(!condition)throw Error("P36 "+label)};
const id="00000000-0000-4000-8000-000000000011",dest="00000000-0000-4000-8000-000000000022",rowid="00000000-0000-4000-8000-000000000033";
ok(validImportId(id)&&safeImportedTransactionLink(id)==="/activity/transaction/"+id,"safe route");
for(const bad of ["../../admin","https://evil","",id+"?token=1"])ok(!validImportId(bad)&&safeImportedTransactionLink(bad)===null,"block injected route");
const account={accountId:id,name:"Checking",kind:"checking",currencyCode:"EUR",institutionName:null};
const dashboard={accounts:[account,{...account,accountId:dest}],imports:[],profiles:[]} as ImportDashboard;
ok(validateSourceFile({name:"bank.csv",size:1024},account)===null,"legitimate source");
ok(validateSourceFile({name:"bank.exe",size:100},account)!==null,"unknown format");
ok(validateSourceFile({name:"bank.csv",size:9000000},account)!==null,"oversize");
const parsed={format:"csv",rows:[{bookedAt:"2026-10-09T12:00:00Z",amountMinor:1200,currencyCode:"EUR"}],statement:{currencyCode:"EUR"}} as unknown as ParsedImportFile;
ok(validateParsedImport(parsed,account).length===0,"verified same currency");
ok(validateParsedImport({...parsed,rows:[{...parsed.rows[0]!,currencyCode:"USD"}]},account).length>0,"mixed currency blocked");
ok(validateParsedImport({...parsed,rows:[{...parsed.rows[0]!,amountMinor:1.01}]},account).length>0,"fractional minor blocked");
const record={recordId:rowid,rowNumber:1,status:"pending",decision:"import",externalId:"bank-id",bookedAt:"2026-10-09T12:00:00Z",amountMinor:-1200,currencyCode:"EUR",proposedType:"transfer",transferAccountId:dest,
categoryId:null,reportingAmountMinor:-1200,exchangeRate:1,duplicateReason:null,duplicateTransactionId:null,duplicateRecordId:null} as ImportPreviewRecord;
const preview={account,import:{importId:id,accountId:id,rowCount:1,status:"review_required",fileSha256:"a".repeat(64),storagePath:"private-file",closingBalanceMinor:12500,closingBalanceAt:"2026-10-09T23:59:00Z",statementCurrency:"EUR"},records:[record],categories:[],accounts:dashboard.accounts,summary:{readyCount:1}} as unknown as ImportPreview;
const audit=previewAudit(preview,dashboard);
ok(audit.blocking.length===0&&audit.ready===1&&audit.willAnchor,"full evidence and closing balance disclosure");
ok(previewAudit({...preview,records:[{...record,transferAccountId:id}]},dashboard).blocking.some(x=>x.includes("different")),"same account transfer blocked");
ok(previewAudit({...preview,records:[{...record,duplicateReason:"source_id"}]},dashboard).blocking.some(x=>x.includes("duplicate")),"strong duplicates never auto posted");
ok(previewAudit({...preview,records:[{...record,decision:"review"}]},dashboard).blocking.length>0,"unresolved cannot partial post");
ok(previewAudit({...preview,import:{...preview.import,fileSha256:null}},dashboard).blocking.some(x=>x.includes("SHA-256")),"custody incomplete");
ok(previewAudit({...preview,import:{...preview.import,status:"completed"}},dashboard).blocking.length>0,"completed not recommitted");
ok(secureRecordUpdate({recordId:rowid,decision:"import",proposedType:"transfer",transferAccountId:dest},record,preview)===null,"valid transfer");
ok(secureRecordUpdate({recordId:rowid,decision:"import",proposedType:"transfer",transferAccountId:id},record,preview)!==null,"self transfer");
ok(secureRecordUpdate({recordId:rowid,decision:"import"}, {...record,duplicateReason:"fingerprint"},preview)!==null,"duplicate review enforced");
ok(secureRecordUpdate({recordId:rowid,decision:"ignore"},record,preview)===null,"intentional ignore");
ok(sourceFileLabel("a".repeat(64)).includes("…")&&sourceFileLabel(null)==="Not available","digest label");
console.log("P36 source integrity, duplicate, staged post and transfer safety tests passed");
