import { availableToSpend, buildSpendingPace, formatActivityDate, percentOf,
  periodTitle, safeMinor, signedActivityAmount, trackedPosition } from "./signal-home-model.js";
import { fixtureOverview, fixtureScenario, fixtureTrend } from "./signal-home.fixture.js";
function assert(v:unknown,message:string):asserts v {if(!v)throw new Error("P28: "+message)}
assert(availableToSpend(fixtureOverview)===63760,"real planned balance used");
assert(availableToSpend(fixtureScenario("no-plan"))===null,"unconfigured budget never treated as zero");
assert(availableToSpend(fixtureScenario("empty"))===null,"empty account does not invent spendable amount");
assert(availableToSpend(fixtureScenario("overrun"))===-15000,"negative plan not hidden");
assert(trackedPosition(fixtureOverview)===287030,"tracked position is not a cash claim");
assert(trackedPosition(fixtureScenario("no-accounts"))===null,"no accounts renders unknown not zero net worth");
assert(safeMinor(Number.MAX_SAFE_INTEGER+1)===null,"unsafe money refused");
assert(safeMinor(NaN)===null,"NaN money refused");
assert(safeMinor(0)===0,"verified zero retained");
assert(percentOf(150,100)===100,"over-budget percentages display cap");
assert(percentOf(-20,100)===0,"negative percentages clamp");
assert(percentOf(20,0)===0,"empty denominator safe");
assert(periodTitle(fixtureOverview).includes("2026"),"period localized");
assert(formatActivityDate("bad date","de-DE","Europe/Berlin")==="Date unavailable","bad timestamps are explicit");
const expense=fixtureOverview.recentActivity[0]!;
const income=fixtureOverview.recentActivity.find(i=>i.transactionType==="income")!;
const evidence=fixtureOverview.recentActivity.find(i=>i.entityKind==="receipt")!;
assert(signedActivityAmount(expense)===-4235,"posted expenses negative");
assert(signedActivityAmount(income)===165000,"posted income positive");
assert(signedActivityAmount(evidence)===null,"receipt evidence never appears as a separate posted expense");
assert(signedActivityAmount({...expense,financialEffect:false})===null,"non-posted entries have no money effect");
assert(signedActivityAmount({...expense,transactionType:"refund",amountMinor:100})===100,"refund restores money");
assert(signedActivityAmount({...expense,transactionType:"transfer",amountMinor:123})===123,"transfer preserved and classified separately");
const points=buildSpendingPace(fixtureOverview,fixtureTrend);
assert(points.length===31,"all period buckets available");
assert(points.filter(p=>p.actualMinor!==null).length===20,"future posted values are not invented");
assert(points[19]?.actualMinor===86240,"cumulative real sample posted spend reconciles");
assert(points[20]?.actualMinor===null,"future posted values unknown");
assert(points[30]?.plannedMinor===150000,"full plan reaches exact monthly amount");
assert(points[0]?.actualMinor===4000,"first posted bucket derives from ledger series");
assert(buildSpendingPace(fixtureOverview,null).length===0,"missing time series shown as unavailable");
assert(buildSpendingPace(fixtureOverview,{...fixtureTrend,profile:{...fixtureTrend.profile,currencyCode:"USD"}}).length===0,"currency mismatch chart refused");
assert(buildSpendingPace(fixtureOverview,{...fixtureTrend,period:{...fixtureTrend.period,start:"2026-09-01T00:00:00Z"}}).length===0,"period mismatch chart refused");
const noPlan=buildSpendingPace(fixtureScenario("no-plan"),fixtureTrend);
assert(noPlan.every(p=>p.plannedMinor===null),"no budget never fabricates comparison line");
assert(noPlan.some(p=>p.actualMinor!==null),"posted spending available without budget");
console.log("P28 domain: 31-day series, source integrity, no-plan, overrun, no-accounts, refunds and receipt-only cases passed");
